# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '4fb2e44d-a0f2-4117-8b7b-5f22f3d0ef62'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'SergioLAB'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    csmParametersFile: 'CreateWebApp/parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
